spring:
  r2dbc:
    #    url: r2dbcs:mysql://139.9.160.14:3306/test
    #    username: Flux
    #    password: root
    password: 123456
    url: r2dbcs:mysql://localhost:3306/webflux?serverTimezone=UTC
    username: root

  redis:
    database: 0
    timeout: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
