spring:
  r2dbc:
#    username: puleya
#    password: 98077777Cm
#    url: r2dbcs:mysql://139.9.160.14:3306/other?serverTimezone=UTC
#    url: r2dbcs:mysql://rm-bp1wsixrgt4h3yfm1so.mysql.rds.aliyuncs.com:3306/other?serverTimezone=UTC
    url: r2dbcs:mysql://localhost:3306/other?serverTimezone=UTC
#    username: other
    username: root
    password: 123456


  redis:
    database: 0
    timeout: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

aliyun:
  accessKeyId: LTAI4G1QW56GoeAu9YMTNPPf
  accessKeySecret: UrUuPuzVwYuzxnQLldMHimzZjRBpVD
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: ad77
    urlPrefix: ad77.oss-cn-beijing.aliyuncs.com
server:
  port: 8082


userService:
  #是否对数据库中的未初始化的数据初始化
  initialization: true
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  user:
    # user的权限字在Redis中失效秒数
    expiretime: 600
  role:
    # role的权限字在Redis中失效秒数
    expiretime: 600
  login:
    #是否允许重复登录
    multiply: false
    #jwt过期的时间(秒)
    jwtExpire: 3600

    #git config --global http.sslVerify "false"