spring:
  r2dbc:

    url: r2dbcs:mysql://localhost:3306/other?serverTimezone=UTC
#    username: other
    username: root
    password:


#  自动触发测试
#  redis:
#    database: 0
#    timeout: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0


server:
  port: 8082